# Generated by Django 5.2.16 on 2026-07-22 23:15

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Profesor / Administrador'), ('STUDENT', 'Estudiante')], default='STUDENT', max_length=10)),
                ('cinturon', models.CharField(choices=[('BLANCO', 'Cinturón Blanco'), ('AZUL', 'Cinturón Azul'), ('MORADO', 'Cinturón Morado'), ('MARRON', 'Cinturón Marrón'), ('NEGRO', 'Cinturón Negro')], default='BLANCO', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('monto_mensualidad', models.DecimalField(decimal_places=2, default=120000.0, max_digits=10)),
                ('dia_vencimiento', models.IntegerField(default=5)),
                ('estado_pago', models.CharField(choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pendiente'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_anio', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('PENDIENTE_VERIFICACION', 'Pendiente de Verificación'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE_VERIFICACION', max_length=25)),
                ('fecha_pago', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('NEQUI', 'Nequi'), ('BANCOLOMBIA', 'Bancolombia'), ('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria')], default='NEQUI', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to=apps.core.models.custom_comprobante_upload_to)),
                ('comprobante_url', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AlertaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(default='RECORDATORIO_VENCIMIENTO', max_length=50)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.userprofile')),
            ],
        ),
    ]
