# Generated by Django 5.2.16 on 2026-07-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAcademia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_mensual_base', models.DecimalField(decimal_places=2, default=120000.0, max_digits=10)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
