# Generated by Django 5.2.16 on 2026-07-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracionacademia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionacademia',
            name='tarifa_mensual_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='monto_mensualidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
